apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=31536000
    haproxy.router.openshift.io/rewrite-target: /
    route.openshift.io/termination: reencrypt
  labels:
    app.kubernetes.io/instance: applications
  name: https-example
  namespace: ingress-test
spec:
  host: https-example-ingress-test.apps.sno.home.naramajac.com.au
  path: /
  port:
    targetPort: https
  httpHeaders:
    actions:
      response:
      - name: Referrer-Policy
        action:
          type: Set
          set:
            value: strict-origin-when-cross-origin
      - name: Feature-Policy
        action:
          type: Set
          set:
            value: camera 'self'; animations 'self'
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
    destinationCACertificate: |
      -----BEGIN CERTIFICATE-----
      MIIF9zCCA9+gAwIBAgIIEnnIiC6qPx4wDQYJKoZIhvcNAQELBQAwfzELMAkGA1UE
      BhMCVVMxFDASBgNVBAoMC1Vuc3BlY2lmaWVkMR8wHQYDVQQLDBZjYS0xMzMxMzE1
      NjUyMDg4NzA4ODk0MRYwFAYDVQQDDA1odHRwcy1leGFtcGxlMSEwHwYJKoZIhvcN
      AQkBFhJyb290QGh0dHBzLWV4YW1wbGUwHhcNMjUwOTMwMjMyNDE5WhcNMjYwOTMw
      MjMyNDE5WjB/MQswCQYDVQQGEwJVUzEUMBIGA1UECgwLVW5zcGVjaWZpZWQxHzAd
      BgNVBAsMFmNhLTEzMzEzMTU2NTIwODg3MDg4OTQxFjAUBgNVBAMMDWh0dHBzLWV4
      YW1wbGUxITAfBgkqhkiG9w0BCQEWEnJvb3RAaHR0cHMtZXhhbXBsZTCCAiIwDQYJ
      KoZIhvcNAQEBBQADggIPADCCAgoCggIBALlr5T2m5TRnM0r+uTao8T3VKydc0Foq
      qv8mXAmoGzhDaT6OC4qI41camIWh23W5TDOtwDGWLAxLZepdq4Ae0m/xLhGKWCpA
      rbfIcrPSjbRXz2VY7fnxGJj1eoIFObgyAAw1NzzdfOi2GAH1vl3tszoLDM6LEsC6
      gqqgyZu7BLV0FiFXHMJpSqeU3KLjYW9ooidZTegUWrm9NKkPPI61iyhx9wUUXjJj
      kWRTwRZ6/ygbkO0qsdGLFpb+dhf6AuOfRLRigz1RJkiZ+JS88VL2RqgQ51ZESKb7
      wjx9LBdfE7b2nSSwAlSKvA5SVdTxC/zBXTmkj1CN9zUqQIimuI2Je16ld7xbSp+7
      0hdJjawhhYgMdDcYC9dDbh66d5wEhpXV+eR0f8Uvwyol6+0GSlXczuGerXPBm4jf
      UmSR1+YxXnvq7at3LBB6UbypS2Z2QaRYDjP4lhKJk1GmLUFFwvsSzkKsMNEQxcyv
      jMdI9r4xHIgs9Yj60miuhcxnrLVRVvGOrfcVfAA4SWx4XsJU+kjAnY3A0bD4HlcC
      fAuvVfuWlXrPN8Ejec2H8GjtzZCw3hFoJMAJhasJi09nsiCN8OaIS/rLWcdW7EKx
      eejLOyzbyBfn25uhUMmpDfnHMo+WBgQNsbc4hNI6KXLSzNZ11ME4ANo39iqrdwsN
      GWbPvqW1/K0vAgMBAAGjdzB1MA4GA1UdDwEB/wQEAwICpDAMBgNVHRMEBTADAQH/
      MBwGA1UdHgQVMBOgETAPgg1odHRwcy1leGFtcGxlMBgGA1UdEQQRMA+CDWh0dHBz
      LWV4YW1wbGUwHQYDVR0OBBYEFBDec5Q6aYCkbD0cokoWzDn3m6saMA0GCSqGSIb3
      DQEBCwUAA4ICAQBdRKRw/J81/2meIzQWpIxm66wZPK/VTg9uP2ve7g4H9116nlmh
      YkVQZ9IN0vhkkyh38FfRT+LeZ8J1bjnGOujiV0QOMrbBWZTK9dVl5QY4rpaV+oCA
      wE+yg54QorgFdrIEScCWu7aFOUcY2y7ym0HoRFjg3dtQSHQjQf3j6Zba9kUUk/vC
      1cSY4YtzJyBXsxFzUNE4oB04rGob1iV40esxUobEKO9q5U5n3eaneDLEoshUOvpH
      cAN+3yYDgkhBr/HHhDu84DxugsFmMYaXkVhhKV78Xh5yJwlTWTfUwgUFDE3ZeLBV
      If8cqI+OKrY8WWv4v/H90lZFBz1fbz++/ZtcmFI1qdBR/VUMjruCatmKIDJYzjrZ
      F6k1FxePTKq5yFchCW9AVgEAd6rD/iqiNIK3NND/YVWmm2CDcPNB2hDC55nsVoYj
      T6sgRzdTdhesUbwNZ3cKM1tp0rl8SD6Z9oAm6J07ea3NaeadRJtabuC0kcnPsUfQ
      CkKnld0X68xCB0C/IQ/Ar7wvwLsDI3ptWJZe2KpzSal0Pgx/EK2ceRBuhEPvNR9l
      UpfpbawvFJdQvQ/7o6Oa5wkoq07HVbiiACccHCQFfvIudUnqN0HHd+uC3ywdBlT0
      Ba/tSIuy4nacYbVwG/BqHf6OB915IfkQcAZ5R6AClxfUVZL0Z/S5qn0plQ==
      -----END CERTIFICATE-----
  to:
    kind: Service
    name: https-example
    weight: 100
  wildcardPolicy: None
