apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true
spec:
  tuningOptions:
    serverTimeout: "600s"
    headerBufferBytes: 13107200
  httpHeaders:
    actions:
      response:
      - name: X-Frame-Options
        action:
          type: Set
          set:
            value: SAMEORIGIN
      - name: Referrer-Policy
        action:
          type: Set
          set:
            value: strict-origin-when-cross-origin
      - name: Feature-Policy
        action:
          type:
          set:
            value: camera 'self'; animations 'self'